server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useSSL=false&serverTimezone=UTC
    username: root
    password: zjw20040929
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml  # 指定 Mapper XML 文件路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 启用 SQL 日志