server:
  port: 8082

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useSSL=false&serverTimezone=UTC
    username: root
    password: zjw20040929
    driver-class-name: com.mysql.cj.jdbc.Driver
